name: Pipeline_OnPush
run-name: ${{github.actor}} is pushing files
on: push
jobs:
    Check-Versions:
                  name: Job for WSL Ubuntu
                  runs-on: ubuntu-latest
                  env:
                    working-directory: /capstone-project/hello-world/
                  steps:
                  - name: StepOne, Repository Check
                    uses: actions/checkout@v3
                  - name: StepTwo, NodeJS
                    uses: actions/setup-node@v3
                    with:
                      node-version: 16.13.1
                  - name: Installing Dependencies
                    run: npm install
                    working-directory: ${{env.working-directory}}
                  - name: Check Version of NPM
                    run: npm version
                    working-directory: ${{env.working-directory}}
    WindowsVersions:
                    name: Job for Windows
                    runs-on: windows-latest
                    env:
                        working-directory: /capstone-project/hello-world/
                    steps:
                    - name: StepOne, Repository Check
                      uses: actions/checkout@v3
                    - name: StepTwo, NodeJS
                      uses: actions/setup-node@v3
                      with:
                        node-version: 16.13.1
                    - name: Installing Dependencies
                      run: npm install
                      working-directory: ${{env.working-directory}}
                    - name: Check Version of NPM
                      run: npm version
                      working-directory: ${{env.working-directory}}
