name: Pipeline_OnPush
run-name: ${{github.actor}} is pushing files
on: [push, pull_request]
default:
  run:
    working-directory: ${{env.working-directory}}
jobs:
    Build_OnUbuntu:
                  name: Job for WSL Ubuntu
                  runs-on: ubuntu-latest
                  env:
                    working-directory: ./capstone_project/hello-world/
                  steps:
                  - name: StepOne, Repository Check
                    uses: actions/checkout@v3
                  - name: StepTwo, NodeJS
                    uses: actions/setup-node@v3
                    with:
                      node-version: 16.13.1
                      cache-dependency-path: ./capstone_project/hello-world/package-lock.json
                  - name: Installing Dependencies
                    run: npm install
                  - name: Check Version of NPM
                    run: npm version
                  - name: Testing Build
                    run: npm test
    Build_OnWindows:
                    name: Job for Windows
                    runs-on: windows-latest
                    env:
                        working-directory: ./capstone_project/hello-world/
                    steps:
                    - name: StepOne, Repository Check
                      uses: actions/checkout@v3
                    - name: StepTwo, NodeJS
                      uses: actions/setup-node@v3
                      with:
                        node-version: 16.13.1
                    - name: Installing Dependencies
                      run: npm install
                    - name: Check Version of NPM
                      run: npm version
                    - name: Testing Build
                      run: npm test
    Deploying_Container_OnUbuntu:
                                name: Making Container
                                runs-on: ubuntu-latest
                                needs: [Build_OnUbuntu]
                                env:
                                  working-directory: ./capstone_project/hello-world/
                                steps:
                                - uses: actions/checkout@v3
                                - name: StepOne:Making Docker Image
                                  run: docker build -t capstone_ubuntu .
                                - name: SetpTwo:Checking Image
                                  run: docker images
    Deploying_Container_OnWindows:
                                name: Making Container
                                runs-on: windows-latest
                                needs: [Build_OnWindows]
                                env:
                                  working-directory: ./capstone_project/hello-world/
                                steps:
                                - uses: actions/checkout@v3
                                - name: StepOne:Making Docker Image
                                  run: docker build -t capstone_windowsArch .
                                - name: SetpTwo:Checking Image
                                  run: docker images


