name: Pipeline_OnPush
run-name: ${{github.actor}} is pushing files
on: [push, pull_request]
jobs:
    Build_OnUbuntu:
                  name: Job for WSL Ubuntu
                  runs-on: ubuntu-latest
                  defaults:
                    run:
                      working-directory: ./capstone_project/hello-world/
                      shell: bash
                  steps:
                  - name: StepOne, Repository Check
                    uses: actions/checkout@v3
                  - name: StepTwo, NodeJS
                    uses: actions/setup-node@v3
                    with:
                      node-version: 16.13.1
                      cache-dependency-path: ./capstone_project/hello-world/package-lock.json
                  - name: Installing Dependencies
                    run: npm install
                  - name: Check Version of NPM
                    run: npm version
                  - name: Testing Build
                    run: npm test
    Build_OnWindows:
                    name: Job for Windows
                    runs-on: windows-latest
                    defaults:
                      run:
                        working-directory: ./capstone_project/hello-world/
                        shell: bash
                    steps:
                    - name: StepOne, Repository Check
                      uses: actions/checkout@v3
                    - name: StepTwo, NodeJS
                      uses: actions/setup-node@v3
                      with:
                        node-version: 16.13.1
                    - name: Installing Dependencies
                      run: npm install
                    - name: Check Version of NPM
                      run: npm version
                    - name: Testing Build
                      run: npm test
    Deploying_Container_OnUbuntu:
                                name: Making Image
                                runs-on: ubuntu-latest
                                defaults:
                                  run:
                                    working-directory: ./capstone_project/hello-world/
                                    shell: bash
                                needs: [Build_OnUbuntu]
                                steps:
                                - uses: actions/checkout@v3
                                - name: Step One:Making Docker Image
                                  run: docker build -t capstone_ubuntu .
                                - name: SetpTwo:Checking Image
                                  run: docker images
                                - name: Step Three:Making Container
                                  run: docker run -d -p 3000:3000 capstone_ubuntu
    Deploying_Container_OnWindows:
                                name: Making Image
                                runs-on: windows-latest
                                defaults:
                                  run:
                                    working-directory: ./capstone_project/hello-world/
                                    shell: bash
                                needs: [Build_OnWindows]
                                steps:
                                - uses: actions/checkout@v3
                                - name: StepOne:Making Docker Image
                                  run: docker build -t capstone_windowsArch .
                                - name: Step Two:Checking Image
                                  run: docker images
                                - name: Step Three:Making Container
                                  run: docker run -d -p 3000:3000 capstone_windowsArch


