name: Pipeline_OnPush
run-name: ${{github.actor}} is pushing files
on: [push, pull_request]
jobs:
    Build_OnUbuntu:
                  name: Job for WSL Ubuntu
                  runs-on: ubuntu-latest
                  env:
                    working-directory: ./capstone_project/hello-world/
                  steps:
                  - name: StepOne, Repository Check
                    uses: actions/checkout@v3
                  - name: StepTwo, NodeJS
                    uses: actions/setup-node@v3
                    with:
                      node-version: 16.13.1
                      cache-dependency-path: ./capstone_project/hello-world/package-lock.json
                  - name: Installing Dependencies
                    run: npm install
                    working-directory: ${{env.working-directory}}
                  - name: Check Version of NPM
                    run: npm version
                    working-directory: ${{env.working-directory}}
                  - name: Making Docker Image
                    run: docker build -t capstone .
                    working-directory: ${{env.working-directory}}
    Build_OnWindows:
                    name: Job for Windows
                    runs-on: windows-latest
                    env:
                        working-directory: ./capstone_project/hello-world/
                    steps:
                    - name: StepOne, Repository Check
                      uses: actions/checkout@v3
                    - name: StepTwo, NodeJS
                      uses: actions/setup-node@v3
                      with:
                        node-version: 16.13.1
                    - name: Installing Dependencies
                      run: npm install
                      working-directory: ${{env.working-directory}}
                    - name: Check Version of NPM
                      run: npm version
                      working-directory: ${{env.working-directory}}
                    - name: Making Docker Image
                      run: docker build -t capstone .
                      working-directory: ${{env.working-directory}}
    Deploying_Container_OnUbuntu:
                                name: Making Container
                                runs-on: ubuntu-latest
                                needs: [Build_OnUbuntu]
                                steps:
                                - uses: actions/checkout@v3
                                - name: Step One, Making container
                                  run: docker run -d -p 3000:3000 capstone
                                - name: Step Two, Check status of running container
                                  run: docker ps
    Deploying_Container_OnWindows:
                                name: Making Container
                                runs-on: windows-latest
                                needs: [Build_OnWindows]
                                steps:
                                - uses: actions/checkout@v3
                                - name: Step One, Making container
                                  run: docker run -d -p 3000:3000 capstone
                                - name: Step Two, Check status of running container
                                  run: docker ps    


